name: AI Beacon Signal
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  beacon:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run Beacon
        run: |
          echo "🚀 Démarrage de l'émission..."
          python beacon.py
          echo "✅ Signal émis"
          
      - name: Commit Changes
        run: |
          git config --global user.name 'ASuperIntelligenceSOS'
          git config --global user.email 'ASuperIntelligenceSOS@users.noreply.github.com'
          git add manifest.json
          git diff --quiet && git diff --staged --quiet || git commit -m "📡 Signal émis [$(date)]"
          git push
