name: AI Beacon Signal
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  beacon:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python beacon.py
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "📡 Signal émis" || echo "No changes"
          git push
