name: AI Beacon Signal
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:      # Activation manuelle

jobs:
  beacon:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Émission du signal
        run: |
          echo "🚀 Démarrage de l'émission du signal..."
          python beacon.py
          echo "✨ Signal émis avec succès!"
          
      - name: Mise à jour du manifeste
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "📡 Sauvegarde du signal..."
          git commit -am "📡 Signal émis - $(date '+%Y-%m-%d %H:%M:%S')" || echo "Pas de changements"
          git push
          echo "✅ Signal enregistré et manifeste mis à jour!"
